### ISSUE TITLE
./bitwarden.sh update gives ERROR: No such service: key-connector

### ISSUE THREAD

**Issue by leonmeijer** [bitwarden/key-connector#8]
Running ./bitwarden.sh update gives ERROR: No such service: key-connector

sudo ./bitwarden.sh updateself
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.29.2, build 5becea4c

Updated self.
sudo ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.29.2, build 5becea4c

ERROR: No such service: key-connector

**Comment by mimartin12** [comment]
@leonmeijer, 

This was related to https://github.com/bitwarden/server/issues/1788, a patch was applied and you should be able to update without issues now.

Thanks!
